energy_consumption/buildings/urls.py
from django.urls import path
from . import views

app_name = 'buildings'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:building_id>', views.meter_detail, name='meter_detail'),
  path('meter_readings/<int:meter_id>', views.meter_readings, name='meter_readings'),
  path('meter_chart/<int:meter_id>', views.meter_chart, name='meter_chart'),
]

energy_consumption/energy_consumption/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from buildings.views import building_upload, meter_upload, reading_upload, meter_detail
urlpatterns = [
    url(r'^', include('pages.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^buildings/', include('buildings.urls')),
    url(r'^upload-building/', building_upload, name="building_upload"),
    url(r'^upload-meter/', meter_upload, name="meter_upload"),
    url(r'^upload-readings/', reading_upload, name="reading_upload"),
]

energy_consumption/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
]

energy_consumption/buildings/models.py
from django.db import models
import re
from django.utils.safestring import mark_safe
from django.urls import reverse
#from .views import meter_detail

class Building(models.Model):
  id = models.IntegerField(primary_key=True)
  name = models.CharField(max_length=100)

  def __str__(self):
    n = self.name.find(" (")
    if n > 0:
      name = self.name[:n]
    else:
      name = self.name
    return name

class Fuel(models.Model):
  fuel = models.CharField(max_length=30, primary_key=True)
  unit = models.CharField(max_length=10)

  def __str__(self):
    return self.fuel

class Meter(models.Model):
  id = models.IntegerField(primary_key=True)
  building = models.ForeignKey(Building, on_delete=models.CASCADE)
  fuel = models.ForeignKey(Fuel, on_delete=models.CASCADE) 

  def __str__(self):
    return str(self.id)

class Readings(models.Model):
  class Meta:
    unique_together = (('meter_id', 'reading_data_time'),)

  meter_id = models.ForeignKey(Meter, on_delete=models.CASCADE)
  reading_data_time = models.DateTimeField('Reading time')
  consumption = models.DecimalField(max_digits=20, decimal_places=4)

energy_consumption/pages/models.py
from django.db import models

# Create your models here.

energy_consumption/buildings/views.py
import csv, io
from django.shortcuts import render
from django.contrib import messages
from django.http import Http404
from django.http import JsonResponse
from .models import Building, Meter, Fuel, Readings


def meter_chart(request, meter_id):
    labels = []
    data = []
    meter = Meter.objects.get(pk=meter_id)
    readingset = meter.readings_set.all()
    for reading in readingset:
        date = reading.reading_data_time.strftime("%m-%d")
        labels.append(date)
        data.append(reading.consumption)
    
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def index(request):
  buildings = Building.objects.order_by()
  context = {'buildings': buildings}
  return render(request, 'buildings/index.html', context)

def meter_detail(request, building_id):
  building = Building.objects.get(pk=building_id)
  return render(request, 'buildings/meter_detail.html', { 'building': building })

def meter_readings(request, meter_id):
  meter = Meter.objects.get(pk=meter_id)
  return render(request, 'buildings/meter_readings.html', { 'meter': meter })

def building_upload(request):    
  # View to upload a csv of buildings
  template = "building_upload.html"
  data = Building.objects.all()
  prompt = {
      'order': 'Order of the CSV should be id, name',
      'buildings': data    
            }

  if request.method == "GET":
      return render(request, template, prompt)    
  csv_file = request.FILES['file']    
  
  # Check for csv file
  if not csv_file.name.endswith('.csv'):
      messages.error(request, 'THIS IS NOT A CSV FILE')    
  data_set = csv_file.read().decode('UTF-8')

  # Stream to loop through each line in the data
  io_string = io.StringIO(data_set)
  next(io_string)
  for column in csv.reader(io_string, delimiter=',', quotechar="|"):
    if not column[0] or column[1]:
      continue 
    _, created = Building.objects.update_or_create(
          id=column[0],
          name=column[1],
      )
  context = {}
  return render(request, template, context)


def meter_upload(request):    
  # View to upload a csv of buildings
  template = "meter_upload.html"
  data = Meter.objects.all()
  prompt = {
      'order': 'Order of the CSV should be building_id, id, fuel, unit',
      'meters': data    
            }

  if request.method == "GET":
      return render(request, template, prompt)    
  csv_file = request.FILES['file']    
  
  # Check for csv file
  if not csv_file.name.endswith('.csv'):
      messages.error(request, 'THIS IS NOT A CSV FILE')    
  data_set = csv_file.read().decode('UTF-8')
  
  # Stream to loop through each line in the data
  io_string = io.StringIO(data_set)
  next(io_string)
  for column in csv.reader(io_string, delimiter=',', quotechar="|"):
    if not column[0] or not column[1] or not column[2] or not column[3]:
      continue 

    _, created_fuel = Fuel.objects.update_or_create(
      fuel=column[2],
      unit=column[3]
    )
    _, created_meter = Meter.objects.update_or_create(
          building=Building.objects.get(pk=column[0]),
          id=column[1],
          fuel=Fuel.objects.get(pk=column[2]),
      )

  context = {}
  return render(request, template, context)


def reading_upload(request):    
  # View to upload a csv of buildings
  template = "meter_upload.html"
  data = Meter.objects.all()
  prompt = {
      'order': 'Order of the CSV should be consumption, meter id, reading date-time',
      'readings': data    
            }

  if request.method == "GET":
      return render(request, template, prompt)    
  csv_file = request.FILES['file']    
  
  # Check for csv file
  if not csv_file.name.endswith('.csv'):
      messages.error(request, 'THIS IS NOT A CSV FILE')    
  data_set = csv_file.read().decode('UTF-8')
  
  # Stream to loop through each line in the data
  io_string = io.StringIO(data_set)
  next(io_string)
  for column in csv.reader(io_string, delimiter=',', quotechar="|"):
    if not column[0] or not column[1] or not column[2]:
      continue 

    _, created_reading = Readings.objects.update_or_create(
      meter_id=Meter.objects.get(pk=column[1]),
      consumption=column[0],
      reading_data_time=column[2]
    )

  context = {}
  return render(request, template, context)

energy_consumption/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request, 'pages/index.html')

energy_consumption/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Energy Consumption {% block title%}{% endblock %}</title>
</head>
<body>
  {% include 'partials/_navbar.html' %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

energy_consumption/templates/building_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div>
<!--                | means OR operator-->
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %}
    {% else %}
    {{order}}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file1"> Upload a file</label>
        <input type="file" id="file1" name="file">
        <small>Only accepts CSV files</small>
        <button type="submit">Upload</button>
    </form>
    {% endif %}
    {% for buiding in buildings %}
    {{building.name}}
    {% endfor %}
</body>
</html>

energy_consumption/templates/buildings/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center mb-3">Buildings</h1>
  {% if buildings %}
  {% for building in buildings %}
  <div class="card mb-3">
    <div class="card-body">
      <p class="lead">{{ building }}</p>
      <a href="{% url 'buildings:meter_detail' building.id %}" class="btn btn-primary btn-sm">Meters</a>
    </div>
  </div>
  {% endfor %}
  {% else %}
    <p>No Data available</p>
  {% endif %}
{% endblock %}

energy_consumption/templates/buildings/meter_detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'buildings:index' %}">Back to Buildings</a>
<h1 class="text-center mb-3">{{ building.name }} </h1>

{% if error_message %}
<p class="alert alert-danger">
 <strong>{{ error_message }}</strong>   
</p>
{% endif %}

<form>
  {% csrf_token %}
  {% for meter in building.meter_set.all %}
  <div class="form-check flex-dir-row">
    <p class="lead"> Meter No: {{ meter.id }}</p>
    <p class="lead">{{ meter.fuel }}</p>
    <a href="{% url 'buildings:meter_readings' meter.id %}" class="btn btn-primary btn-sm">View Data</a>
  </div>
  {% endfor %}
</form>
{% endblock %}

energy_consumption/templates/buildings/meter_readings.html
{% extends 'base.html' %}

{% block content %}

  <div id="container">
    <label>{{ meter.fuel }} Consumption</label>
    <canvas id="meter_chart" data-url="{% url 'buildings:meter_chart' meter.id %}"></canvas>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $meterChart = $("#meter_chart");
      $.ajax({
        url: $meterChart.data("url"),
        success: function (data) {

          var ctx = $meterChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: '{{ meter.fuel }} Consumption / {{ meter.fuel.unit }}',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Meter Readings'
              },
              scales: {
                yAxes: [{
                  scaleLabel: {
                    display: true,
                    labelString: 'Consumption / {{ meter.fuel.unit }}'
                  }
                }]
              }
            }
          });

        }
      });

    });

  </script>

{% endblock %}

energy_consumption/templates/meter_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div>
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %}
    {% else %}
    {{order}}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file1"> Upload a file</label>
        <input type="file" id="file1" name="file">
        <small>Only accepts CSV files</small>
        <button type="submit">Upload</button>
    </form>
    {% endif %}
</body>
</html>

energy_consumption/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome to Meter Readings</h1>
    <p>Click below to view the Buildings</p>
    <a class="btn btn-dark" href="{% url 'buildings:index' %}">
      View Buildings
    </a>
  </div>
</div>
{% endblock %}

energy_consumption/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">Energy Consumption</a>
    <a class="navbar-brand" href="/upload-building">Upload Buildings</a>
    <a class="navbar-brand" href="/upload-meter">Upload Meters</a>
    <a class="navbar-brand" href="/upload-readings">Upload Readings</a>
  </div>
</nav>

energy_consumption/templates/reading_upload.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div>
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %}
    {% else %}
    {{order}}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file1"> Upload a file</label>
        <input type="file" id="file1" name="file">
        <small>Only accepts CSV files</small>
        <button type="submit">Upload</button>
    </form>
    {% endif %}
    {% for reading in readings %}
    {{ reading.meter_id }}
    {% endfor %}
</body>
</html>